### ISSUE TITLE
Already Seen?

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#110]
This is more a design question. The "Already Seen" label is standard in PFE, but we haven't considered yet if it should be added to ASM.

**Comment by wgranger** [comment]
Tagging @beckyrother

**Comment by beckyrother** [comment]
Good question! Yes, we should add it if it's possible to get to a subject you've already seen. 
I'll mock something up for ya

**Comment by beckyrother** [comment]
https://invis.io/5XE3CXHKB#/259876226_Already_Seen

This uses another font, [Oswald](https://fonts.google.com/specimen/Oswald), from google fonts. Let me know if this is too many fonts.

**Comment by wgranger** [comment]
What happens when "what's this" is clicked? Is it necessary we have a description of this?

**Comment by beckyrother** [comment]
I think we'd talked about people wondering why they're being shown a subject they've already worked on. @shaunanoordin had an idea what would happen if you clicked that I think? From my understanding it would be a little popup like the subject info box that explains why you're seeing this subject?
