### ISSUE TITLE
How do we handle having No Subject?

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#121]
## Investigation Required
Here's a question: when the Panoptes Subject queue serves no further Subjects, are we able to handle it properly? Will our app gracefully say, "lol sorry no moar pages 4 u", or will it crash when it tries to display Subject data that doesn't exist?

Also, side note: do we have a proper status/notification system for these sort of things? I thought we did, but my mind is blank.

### Status
Needs to be addressed - probably in the Subjects duck, plus a popup notification/status element - but this doesn't need to be rushed for the Beta.

**Comment by beckyrother** [comment]
We do have a [style for "already seen" ](https://github.com/zooniverse/liberating-the-liberator/issues/110#issuecomment-338684212 )that can also be used when there are no new subjects: 

![bpl-no new subjects](https://user-images.githubusercontent.com/1392130/32336851-6fd395ba-bfbe-11e7-902a-23bb56a7cf6c.png)
