### ISSUE TITLE
Design notes

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/anti-slavery-manuscripts#133]
Hi, here's where I'm going to post all of my design notes. I'll post an image with notes, then re-post those notes in a list. Please check off the list item when it's been implemented. **Please note that some of the typed-out notes are _not_ on the picture.**
***
# Home
- [x] Change navigation font to Playfair display all caps
- [x] Increase body copy font-size to 1.1 em
- [x] Add the IMLS logo to the right of the BPL logo
- [x] Remove the errant `0` above `Community` 
- [x] Add 10px spacing between the two stats columns
- [x] Write more in `Message from the researchers` – _Sam is writing_
- [x] Social icons rearranged _Will is working on?_

![asm-home-br](https://user-images.githubusercontent.com/1392130/32245002-5dda8534-be48-11e7-8225-0530cc6c9359.png)

***
# About 
- [x] Move `About the Collection` down 0.2em
- [x] Remove letter-spacing on `the` from `About the Collection`
- [x] Move `About the Project` link up 1em
- [x] Body copy should be 0.9em
- [x] Reduce padding around the `Significance...` section to 4em
- [x] All headlines (h2) should be Playfair Display
- [x] **mobile/small screens** timeline turns into a list at viewport size 640px
- [x] keep the distance between Charles Lenox Remond and Maria Weston Chapman always 50px
- [x] `start transcribing` at the bottom looks smaller than the rest of the links on the page

![asm-about-br](https://user-images.githubusercontent.com/1392130/32245261-2c0bd9b2-be49-11e7-9c72-a6c7806153af.png)

***
# About the project
- [x] Remove the letter-spacing from headlines
- [ ] Add "research partners section (design to come)

***
# Classifications
- [x] Remove the border(s) on the box around subjects
- [x] Change `Related Images` on the filmstrip viewer to say `Other Pages` 
- [x] Change that font color to #efebe3 
- [x] Add 1em margin to the top and bottom of the divider line between Navigator and Toolbar
- [x] Add tutorial button above Field Guide
- [x] `Contrast` actually inverts the image – just label the button `Invert Colors`
- [x] Remove the space between 90 and º in `Rotate 90 º`

![asm-classify-br](https://user-images.githubusercontent.com/1392130/32245941-773a4d9a-be4b-11e7-9b02-8c75be9b1de5.png)

***
## Add to collection
- [x] Buttons should not have a shadow
- [x] Text input box the same height as the Collections dropdown 
- [x] Disable both buttons (50% transparency) until one of the options is chosen
- [x] `Or create a new Collection` (don't capitalize Create) in Cormorant
- [x] Space between the checkbox and `Private`
- [x] Move the closing X down into the box and style it the same way as the other x's on this page

![anti-slavery_manuscripts](https://user-images.githubusercontent.com/1392130/32297386-05bb3b84-bf1d-11e7-82c6-e3dc9aec1cf4.png)

**Comment by beckyrother** [comment]
IMLS logo: 
![imls-logo](https://user-images.githubusercontent.com/1392130/32246759-0e07886c-be4e-11e7-9e35-917345e50bd7.png)

**Comment by beckyrother** [comment]
Please add this image to the About the Collection by the `The Boston Public Library and the Anti-Slavery Collection of Distinction` section 
![bpl-image](https://user-images.githubusercontent.com/1392130/32247372-1b27dc84-be50-11e7-86eb-1272b0f29f77.jpg)

**Comment by snblickhan** [comment]
Typo in "About the Project" section: 

> one of the largest and most important collections of abolitionist~~s~~ material in the United States
