### ISSUE TITLE
Design: updating subject loading screen

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/anti-slavery-manuscripts#137]
Tangentially related to https://github.com/zooniverse/liberating-the-liberator/issues/121 

Instead of the blue circle inside the subject area, can we use this https://codepen.io/beckyrother/pen/BmjKWj centered in the grey box.

**Comment by wgranger** [comment]
This should be fine. You're talking about while we're waiting for the subject to load? The only difference between this and the main loader is the blue background? Correct me if I'm wrong.

**Comment by beckyrother** [comment]
Yes, and it says "subject loading" instead of just "loading"
