### ISSUE TITLE
Individual Users Should See Grayed Out (Retired) Lines

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#146]
This is something that passed under the radar in planning. It was my assumption that users in the individual group would _never_ see previous annotations from Caesar's reducer. However, users in the individual group should see a line that has been previously annotated *only* if that individual line has reached retirement and is grayed out.

**Comment by shaunanoordin** [comment]
On a related note, this just occurred to me: how _long_ will it take before these retired aggregation lines start to appear? What about not-retired aggregation lines?

I just realised that for a long time, our users - especially our Beta testers - will only see what _looks like_ a non-collaborative  transcription system.

**Comment by wgranger** [comment]
Hmm, I'd think it would take a while for the grayed out lines to appear. It seems at minimum, three annotations for each line would be needed, and they would need to agree.

I'd think, for collaborative users, the non-retired aggregation (red) lines would appear with at least one previous annotation.
