### ISSUE TITLE
A Tale of Two Workflows

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#148]
## Core Change Request
Instead of having only 1 workflow split between our A-split (solo transcription) and B-split (collaborative transcription) users, we now need **two Panoptes workflows,** one for each split.

This is a significant change to the project's planned implementation, so please note some...

### Very Important Notes
1. **Each Panoptes workflow is an exact mirror of the other.** Same subjects, same tasks, etc, just different users.
2. As of the latest discussion on the ZooSlack's IMLS channel, the A-B Split will only **run for a month or two** before we finally choose to go all in with either solo transcription or collaborative transcription.

The rationale for this mostly comes down to the scientific data; the research team wants to be able to much more easily separate the data input coming in from Split A and Split B.

### Implementation Notes
A few things to be aware of in implementing this.

**PFE:**
- [ ] The A-split and B-split workflows need to match each other, _including the task label._ Be super aware that the first Annotation task should be **T1, not T0.**
- [ ] The act of replicating the workflows needs to be replicated on both production and staging.

**Coleman & Caesar:**
- [ ] Coleman needs to be informed of the new workflow IDs.
 
**Front-End Coding:**
- [ ] Don't forget the config.js file for both staging and production.
- [ ] [MAJOR] The lifecycle for the app needs to be changed; notably, the Seven-Ten A/B split needs to be completed _before_ the app can be displayed to the user. 
  - Very very specifically, the lifecycle on the app loading event needs to be like this...
```
1. Show "Loading app..." status
2. Load the Project data
3. Get logged in user details (if applicable)
4. (requires 3's success) Select the A-B split from Seven-Ten (failsafe required in case Seven Ten is dead)
5. (requires 4's success, or failsafe) Load the Workflow data 
6. (requires 2 and 5's successes) Hide "Loading app..." status, show the full app
```

### Status
This is now a major issue that needs to be tackled for the ASM Beta.

**Comment by CKrawczyk** [comment]
A quick note about the task label: the labels are used by Caesar to extract the proper annotation from a classification.  As long as it does not change after Caesar is set up it does not matter what the labels are (or if they are different from workflow to workflow).

**Comment by wgranger** [comment]
This is about taken care of with a recent PR, except for the first task being "T1" error. Do you know how to correct this issue?

@shaunanoordin
