### ISSUE TITLE
Add Keyboard Shortcuts

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#172]
This will help improve accessibility #107, and will also help the overall functionality of the site. Upon initial conversation, keyboard shortcuts can be added in the classifier for:

- Toggle previous marks
- Toggle between navigate/annotate

**Comment by beckyrother** [comment]
Can I also add:
- Shift-Enter to submit classification / close transcribe box
- Esc to cancel transcribe box

**Comment by wgranger** [comment]
Nice. Also, is there a way we should indicate these options to users? On the classifier somewhere? I'm afraid it might get lost in something like a tutorial, but don't want it to crowd up too much space.

**Comment by beckyrother** [comment]
What if we do another item in the toolbar with a `fa-keyboard-o` icon.
Maybe just list them in a grid the same way as in the subject info?

**Comment by beckyrother** [comment]
* command/control-enter to submit
