### ISSUE TITLE
Add Hover State to Grayed Out Lines

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#176]
Add "this line has been transcribed!" hover state to grayed out lines to notify user to move along.

**Comment by wgranger** [comment]
@beckyrother Thoughts here? I made this pretty quickly. It appears on hover and follows aside the mouse if you're on the line/dots. However, I'm curious if the hover should only be on a dot since the line has such a small area to hover over.

<img width="466" alt="screen shot 2017-11-27 at 9 02 20 am" src="https://user-images.githubusercontent.com/14099077/33273071-caf51a94-d351-11e7-8c82-1dd6abc994a9.png">

**Comment by beckyrother** [comment]
Nice! I'd just add maybe 5px more padding all around the text, remove the corner radius, and use background color #F4F0E8
