### ISSUE TITLE
Add Zoo team bios to About Us page

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/anti-slavery-manuscripts#184]
_please comment with your bio_

Victoria's bio: 
Victoria Van Hyning is a British Academy postdoctoral fellow in English literature at Oxford, and is the humanities PI at Zooniverse. She has worked on Science Gossip, AnnoTate, and Shakespeare’s World, and led the IMLS grant proposal with Laura Trouille of the Adler, which funds work on AntiSlavery Manuscripts. and other transcription projects.

Becky:
Becky Rother is the Zooniverse designer, working with both the research team and Zooniverse developers to create a fun, engaging product to help researchers achieve their goals. With a background in mobile apps and product design and a degree in journalism, she's using her powers for good.

**Comment by CKrawczyk** [comment]
Coleman:
Coleman Krawczyk is a postdoctoral researcher at the University of Portsmouth, UK.  With a background in astrophysics, he is currently working as a data scientist for the Zooniverse.  In particular he is working on general purpose aggregation tools including the ones used for AnitSlavery Manuscripts.

**Comment by shaunanoordin** [comment]
I have... I have no idea how to write a non-funny, non-ridiculous bio. Give me several minutes.

**Comment by shaunanoordin** [comment]
_As a Zooniverse web developer, Shaun A. Noordin writes code for fun and solves puzzles for a living. Although his favourite form of reading involves wordless panels in comic books, he is supremely proud to contribute to the Anti-Slavery Manuscripts transcription project._

**Comment by wgranger** [comment]
Will joined the Adler Planetarium in 2016 as a front-end developer for the Zooniverse. In the past, he has taught English overseas, toured in bands, and helped open a music venue in Alabama.

**Comment by snblickhan** [comment]
Samantha Blickhan is the IMLS Postdoctoral Fellow for Zooniverse, working on text and audio transcription projects. Her research interests include medieval manuscripts, music notation, and histories of writing.
