### ISSUE TITLE
User cannot submit Classification

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#216]
## Issue needs investigating
A user encountered an error message at the submission process of a fully transcribed/annotated letter.

- Original report: https://www.zooniverse.org/projects/bostonpubliclibrary/anti-slavery-manuscripts/talk/1183/477165
  - **Letter finished but system would not accept it**
  - _Finished a letter but had a one hour gap before the last page. The last page had problems (post mark, different orientation of inscription etc) and when I finished it would not accept the letter. Are all the four pages of work wasted - I hope not!_
- Worth double-checking our previous fix. https://github.com/zooniverse/anti-slavery-manuscripts/pull/192
- Problem is, this is such a vague error that once again we're searching for a noodle in a haystack. (We could have used a magnet if it was a needle.)
- **We may need an error logging system.** Shaun: check Rollbar that Cam invited you to.
- The queue system ("send Classifications later") may be a way to pave over visible errors, but we may still need to find the root cause

**Comment by shaunanoordin** [comment]
Update: Fix #192 seems to be in place, so this bug is an exciting new pain in the butt to debug.

**Comment by wgranger** [comment]
Note: I've tried transcribing on the final page of a subject (with the next subject being less pages) to see if we had a similar error as that from #192, but everything looked alright there.

A potential step in the right direction was to try logging errors to GA.
