### ISSUE TITLE
Implement "Already Seen" banner

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#218]
## Feature Required
When the ASM Classifier serves a Subject that the user has already seen, we need some sort of banner/sign/etc indicating this is the case.

### Status
Medium priority. Doesn't affect functionality, but it assuages users' concerns when (after the ASM runs out of new Subjects to serve) the users see a document they've already spent hours classifying prior, but with their work apparently "lost". (Explanation: their work isn't lost; it has already been submitted to Panoptes and therefore doesn't need to be shown ala Saved Progress Classifications.)

**Comment by wgranger** [comment]
Copy of #110. I'll try to get this up by the end of the week.
