### ISSUE TITLE
Change "Annotate" Button to "Transcribe"

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/anti-slavery-manuscripts#239]
- [x] Change button name in Toolbar

Mentions of Annotate button to check/change:
- [x] Directions

About page:
- [x] Significance of the Correspondence > 2nd paragraph: please change "blacks" to "Black people"

**Comment by beckyrother** [comment]
two minor changes on the About page:

- [ ] Significance > 2nd paragraph: capitalize "Blacks" 
- [ ] Significance > 3rd paragraph: "In addition, while the collection ~~documents~~ **describes**  years of concerted effort on behalf...

**Comment by snblickhan** [comment]
@beckyrother For the first change, as well as capitalizing, I'd like to change it to "Black people" (following the example set by other projects). Nice catch, btw.

As for the second change, I think it may actually be better to keep it as "documents", since it's referring to the collection as a whole, not the contents of specific letters.

**Comment by beckyrother** [comment]
@snblickhan Agreed on the first point. 
On the second, I was confused because "documents" is being used as a verb, while in most other places it's used as a noun. Just looking for another word that does the same thing but isn't quite as confusing.

**Comment by snblickhan** [comment]
@wgranger just a note that I removed the things on the checklist that we'll only be able to be complete after these changes are merged (tutorial images, etc). Only thing left is the About page change I just added to the original list. Should those merge along with the slight typos & home page note re: ASM not being mobile-friendly?

**Comment by wgranger** [comment]
They're already in the PR. See #246
