### ISSUE TITLE
Switch to collaborative workflow only

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/anti-slavery-manuscripts#279]
Need to temporarily pause project while work happens. This should happen in two phases:

Phase one (temporarily disable classifier):
- [x] Disable independent workflow (but don't delete entirely)
- [x] Add banner: "The project is undergoing some light maintenance and will resume shortly, with new letters to transcribe!"
- [x] Remove survey link

Phase two (reopen collaborative):
- [x] Re-open collaborative workflow with new subjects
- [x] Remove banner
- [x] Remove workflow options so volunteers go directly to collaborative workflow

**Comment by wgranger** [comment]
Finished with #281 

Will de deployed Monday, 11/26/18
