### ISSUE TITLE
Edit text on "Submit Classification" screen

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/anti-slavery-manuscripts#282]
CURRENT TEXT:
Have all the pages in this letter been completely transcribed? (i.e. either by yourself or other users.)
Yes, all pages are complete.
No, there are still pages to be completed.

- [ ] NEW TEXT:
Have all the pages in this letter been completely transcribed? (i.e. is the entire letter underlined in grey?)
Yes, all pages are complete.
No, there are still pages to be completed.

**Comment by wgranger** [comment]
This change was needed in the project builder, as the text in the classification submit box is derived from task two of each workflow.
