### ISSUE TITLE
Submit Classifications

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#41]
## Feature Needed
* Once a user has finished looking at a Subject, they must be able to submit that Classification to Panoptes
* Questions:
  * What is the correct JSON structure of a Classification?
    * For this project we can either build this structure from foreknowledge, OR
    * If we're awesome, we'll build the structure based on the Project's default workflow. (It's black sorcery to me.)
    * BE PREPARED: Multi-image Subjects will introduce some funky-fresh challenges!
  * What are the steps/what's the flow for this "Finish my Classification For This Subject And Submit It" action? e.g.:
    * Click 'Finish Annotation'
    * User is asked, "Did you finish annotate everything on this page?"
      * A. Click ''Naw, I'm not done yet" -> Cancel out
      * B. Click "Naw, but I've done all I can" -> Submit Classification (with metadata: Subject isn't fully Classified), then Fetch New Subject.
      * C. Click "Yeah dawg, that's everything" -> Submit Classification (with metadata: Subject is done), then Fetch New Subject.
  * (The above example is based on the current AnnoTate workflow, so obviously we need to think of the exact steps once we have agreement/collaboration mechanisms built in.)

**Comment by wgranger** [comment]
This basic functionality has been implemented for beta launch.
