### ISSUE TITLE
When the <Dialog /> is open, prevent interaction with background items

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#59]
## Fix Required
* Following PR #56 and #57, which adds the new resizable, draggable <Dialog /> component (for the Annotation Text popup and the Subject Info/Metadata popup respectively), one issue needs to be addressed.
* Notably, when the Annotation Text popup is open, the user can STILL make new annotations.
* The popup doesn't block interaction with the background elements, which can lead to unintended behaviour.

Tagging @wgranger

**Comment by eatyourgreens** [comment]
You probably want to make sure that keyboard interactions are limited to the dialog too, when it's open.

**Comment by wgranger** [comment]
Ahh, good point @eatyourgreens. Is that mainly handled by adjusting the tabindex when the dialog is open?

**Comment by eatyourgreens** [comment]
I had a go at writing a [ModalFocus](/zooniverse/Panoptes-Front-End/blob/master/app/components/modal-focus.jsx) for PFE that traps keyboard focus inside its children. Feel free to copy it. You have to explicitly focus one of its children when the dialog opens, but it then listens to keyboard events and prevents you from tabbing out of the component.

It probably doesn't catch all possible keyboard interactions but it should work for the situation where you open a box, optionally tab through a form and enter/esc to close it when finished.

**Comment by eatyourgreens** [comment]
Or maybe we should move that component into ZRC?

**Comment by wgranger** [comment]
In the long term, that would be helpful, as I can see this component being used a good bit in the future, especially with transcription projects. However, does the component in PFE use Brian's modal-form? In our use case here, it is important the modal can be dragged and resized, which I'm not sure is available in that modal.

**Comment by eatyourgreens** [comment]
That component is a wrapper, so you could put it around Brian's modal form. It isn't a modal in its own right, just a decorator that adds keyboard listeners.

**Comment by eatyourgreens** [comment]
Here's [an example](/zooniverse/Panoptes-Front-End/blob/d88ba36a1065fd958ad19d404403c3031ddd5b1c/app/classifier/drawing-tools/root.cjsx#L66-L75) where it's used with a modal form component.
